"""empty message

Revision ID: e709feac3257
Revises: 
Create Date: 2024-09-07 19:43:23.954185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e709feac3257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email')),
    sa.UniqueConstraint('username', name=op.f('uq_customers_username'))
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('arrival_port', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('freight_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments'))
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_containers_customer_id_customers')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_containers_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_containers')),
    sa.UniqueConstraint('container_number', name=op.f('uq_containers_container_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('containers')
    op.drop_table('shipments')
    op.drop_table('customers')
    # ### end Alembic commands ###
